// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFVPsu-f9pagSNaQ2DPZPIMWnob7eHGDU',
    appId: '1:71874806278:web:88f5d66045b9f05f90f987',
    messagingSenderId: '71874806278',
    projectId: 'projetflutter-1c088',
    authDomain: 'projetflutter-1c088.firebaseapp.com',
    storageBucket: 'projetflutter-1c088.firebasestorage.app',
    measurementId: 'G-1BY7RFQ5DK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzDnYr8YvT9pYdoFoINL_1uBkoJepoON0',
    appId: '1:71874806278:android:720f99e767c008f690f987',
    messagingSenderId: '71874806278',
    projectId: 'projetflutter-1c088',
    storageBucket: 'projetflutter-1c088.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFVPsu-f9pagSNaQ2DPZPIMWnob7eHGDU',
    appId: '1:71874806278:web:9f00c2ae66d262b890f987',
    messagingSenderId: '71874806278',
    projectId: 'projetflutter-1c088',
    authDomain: 'projetflutter-1c088.firebaseapp.com',
    storageBucket: 'projetflutter-1c088.firebasestorage.app',
    measurementId: 'G-7806Z2S74X',
  );
}
